### ISSUE TITLE
triangle 프로젝트에서 궁금한점 (나중에 줌에서 물어볼거같은것)

### ISSUE THREAD

**Issue by sgju-placea** [YeonjuOHYE/WebGL#9]
triangle 프로젝트에서 궁금한점

--- 
![image](https://user-images.githubusercontent.com/36391996/102002478-3917e280-3d40-11eb-8c8b-c354cbb749ab.png)
- attribute 나 varying 등 모르는 키워드들이 보이는데 이건뭘까?
- vertex shader와 fragment shader 간의 변수 공유는 이름이 같으면 되는건가?

---
  configureTriangleVertices(gl, program);
  configureTriangleColors(gl, program);
이 두개에 대한 설명. 
- configure는 먼가를 만들때마다 적는것일까?
- buffer는 언제 쓰고 언제 안쓰는걸까?
- vertexAttribPointer, enableVertexAttribArray 는 뭘까

**Comment by YeonjuOHYE** [comment]
https://webglfundamentals.org/webgl/lessons/ko/webgl-fundamentals.html
